package com.hotel.hotel_backend.dto.response;

import com.hotel.hotel_backend.entity.AssignmentType;
import com.hotel.hotel_backend.entity.RoomCategory;
import com.hotel.hotel_backend.entity.RoomUnitStatus;

import java.time.LocalDate;
import java.time.OffsetDateTime;

public record HotelRoomUnitResponse(
        Long id,
        Long roomId,
        String roomName,
        RoomCategory roomCategory,
        String roomCoverImageUrl,
        String roomNumber,
        Integer floor,
        RoomUnitStatus status,
        String notes,
        String guestName,
        String coverImageUrl,
        boolean autoGenerated,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt,
        // ── Thông tin chiếm dụng cho NGÀY đang xem (null nếu phòng trống ngày đó) ──
        /** Ngày mà status được suy ra (= tham số ?date hoặc hôm nay). */
        LocalDate effectiveDate,
        /** Booking đang chiếm phòng vào effectiveDate (null nếu không phải do booking). */
        Long bookingId,
        /** Loại chiếm dụng vào effectiveDate: BOOKING / MAINTENANCE / BLOCK. */
        AssignmentType assignmentType,
        /** Id bản ghi assignment phủ ngày này — dùng để gỡ khoá bảo trì/block. */
        Long assignmentId
) {}
