package com.hotel.hotel_backend.service;

import com.hotel.hotel_backend.dto.request.CreateRoomUnitRequest;
import com.hotel.hotel_backend.dto.request.UpdateRoomUnitRequest;
import com.hotel.hotel_backend.dto.response.HotelRoomUnitResponse;
import com.hotel.hotel_backend.dto.response.RoomUnitResponse;
import com.hotel.hotel_backend.dto.response.RoomUnitSummaryResponse;
import com.hotel.hotel_backend.entity.AssignmentType;
import com.hotel.hotel_backend.entity.Booking;
import com.hotel.hotel_backend.entity.BookingStatus;
import com.hotel.hotel_backend.entity.Hotel;
import com.hotel.hotel_backend.entity.Room;
import com.hotel.hotel_backend.entity.RoomUnit;
import com.hotel.hotel_backend.entity.RoomUnitAssignment;
import com.hotel.hotel_backend.entity.RoomUnitStatus;
import com.hotel.hotel_backend.exception.ApiException;
import com.hotel.hotel_backend.exception.ErrorCode;
import com.hotel.hotel_backend.repository.HotelRepository;
import com.hotel.hotel_backend.repository.RoomRepository;
import com.hotel.hotel_backend.repository.RoomUnitAssignmentRepository;
import com.hotel.hotel_backend.repository.RoomUnitRepository;
import com.hotel.hotel_backend.service.InventoryService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

@Service
@RequiredArgsConstructor
@Transactional
public class RoomUnitService {

    /** Booking ở các trạng thái này mới thực sự "giữ" phòng cho ngày đang xem. */
    private static final Set<BookingStatus> ACTIVE_STATUSES =
            Set.of(BookingStatus.CONFIRMED, BookingStatus.CHECKED_IN);

    private final RoomUnitRepository roomUnitRepository;
    private final RoomRepository roomRepository;
    private final HotelRepository hotelRepository;
    private final SecurityService securityService;
    private final InventoryService inventoryService;
    private final RoomUnitAssignmentRepository assignmentRepository;

    @Transactional(readOnly = true)
    public List<RoomUnitResponse> getUnits(Long roomId) {
        Room room = findOwnedRoom(roomId);
        return roomUnitRepository.findByRoomIdOrderByFloorAscRoomNumberAsc(room.getId())
                .stream()
                .map(this::mapToResponse)
                .toList();
    }

    public RoomUnitResponse create(Long roomId, CreateRoomUnitRequest request) {
        // Acquire row-level write lock to prevent TOCTOU race on the capacity check.
        Room room = findOwnedRoomForUpdate(roomId);

        if (request.roomNumber() != null && !request.roomNumber().isBlank()) {
            String normalized = request.roomNumber().trim();
            Long hotelId = room.getHotel().getId();
            if (roomUnitRepository.countByHotelIdAndRoomNumber(hotelId, normalized, null) > 0) {
                throw new ApiException(ErrorCode.CONFLICT,
                        "Số phòng \"" + normalized + "\" đã tồn tại trong cơ sở này");
            }
        }

        long currentCount = roomUnitRepository.countByRoomId(room.getId());
        if (currentCount >= room.getQuantity()) {
            throw new ApiException(ErrorCode.VALIDATION_ERROR,
                    "Đã đủ " + room.getQuantity() + " phòng theo cấu hình loại phòng. " +
                    "Hãy tăng số lượng trong cài đặt loại phòng trước.");
        }

        RoomUnitStatus initialStatus = request.status() != null ? request.status() : RoomUnitStatus.AVAILABLE;

        RoomUnit unit = new RoomUnit();
        unit.setRoom(room);
        unit.setRoomNumber(request.roomNumber() == null ? null : request.roomNumber().trim());
        unit.setFloor(request.floor());
        unit.setStatus(initialStatus);
        unit.setNotes(request.notes());
        unit.setGuestName(request.guestName());
        unit.setAutoGenerated(false);

        roomUnitRepository.save(unit);

        if (initialStatus == RoomUnitStatus.MAINTENANCE) {
            long nonMaintenance = roomUnitRepository.countByRoomIdAndStatusNot(
                    room.getId(), RoomUnitStatus.MAINTENANCE);
            inventoryService.capInventory(room.getId(), (int) nonMaintenance);
        }

        return mapToResponse(unit);
    }

    public RoomUnitResponse update(Long roomId, Long unitId, UpdateRoomUnitRequest request) {
        Room room = findOwnedRoom(roomId);
        RoomUnit unit = findUnit(unitId, room.getId());

        if ((request.status() == RoomUnitStatus.RESERVED || request.status() == RoomUnitStatus.OCCUPIED)
                && (unit.getStatus() == RoomUnitStatus.RESERVED || unit.getStatus() == RoomUnitStatus.OCCUPIED)
                && unit.getNotes() != null && !unit.getNotes().isBlank()
                && request.notes() != null && !request.notes().isBlank()
                && !unit.getNotes().equals(request.notes())) {
            throw new ApiException(ErrorCode.CONFLICT,
                    "Phòng này đã được gán cho một booking khác. Vui lòng chọn phòng khác.");
        }

        if (request.roomNumber() != null && !request.roomNumber().isBlank()) {
            String normalized = request.roomNumber().trim();
            Long hotelId = room.getHotel().getId();
            if (roomUnitRepository.countByHotelIdAndRoomNumber(hotelId, normalized, unit.getId()) > 0) {
                throw new ApiException(ErrorCode.CONFLICT,
                        "Số phòng \"" + normalized + "\" đã tồn tại trong cơ sở này");
            }
            unit.setRoomNumber(normalized);
        } else {
            unit.setRoomNumber(null);
        }

        RoomUnitStatus oldStatus = unit.getStatus();
        RoomUnitStatus newStatus = request.status();

        unit.setFloor(request.floor());
        unit.setStatus(newStatus);
        unit.setNotes(request.notes());
        unit.setGuestName(request.guestName());
        unit.setCoverImageUrl(request.coverImageUrl());

        // Sync DailyInventory when transitioning to/from MAINTENANCE.
        // MAINTENANCE phòng bị tắt hoạt động → giảm availableRooms để tránh overbooking.
        // Khi phục hồi → tăng lại 1 slot, không vượt Room.quantity.
        if (oldStatus != newStatus) {
            boolean wasInMaintenance = oldStatus == RoomUnitStatus.MAINTENANCE;
            boolean isInMaintenance  = newStatus == RoomUnitStatus.MAINTENANCE;
            if (wasInMaintenance != isInMaintenance) {
                if (isInMaintenance) {
                    long nonMaintenance = roomUnitRepository.countByRoomIdAndStatusNot(
                            room.getId(), RoomUnitStatus.MAINTENANCE);
                    inventoryService.capInventory(room.getId(), (int) nonMaintenance);
                } else {
                    inventoryService.restoreOneUnit(room.getId(), room.getQuantity());
                }
            }
        }

        return mapToResponse(unit);
    }

    public void delete(Long roomId, Long unitId) {
        Room room = findOwnedRoom(roomId);
        RoomUnit unit = findUnit(unitId, room.getId());

        if (unit.getStatus() == RoomUnitStatus.OCCUPIED || unit.getStatus() == RoomUnitStatus.RESERVED) {
            throw new ApiException(ErrorCode.VALIDATION_ERROR,
                    "Không thể xóa phòng đang có khách hoặc đã được đặt. " +
                    "Đảm bảo trạng thái không còn là OCCUPIED/RESERVED trước khi xóa.");
        }

        roomUnitRepository.delete(unit);

        // Decrement declared quantity to match actual physical count.
        int newQuantity = Math.max(0, room.getQuantity() - 1);
        room.setQuantity(newQuantity);

        // Re-sync DailyInventory: cap to the lesser of newQuantity and actual non-maintenance count
        // to avoid overbooking when maintenance units still exist.
        long nonMaintenance = roomUnitRepository.countByRoomIdAndStatusNot(
                room.getId(), RoomUnitStatus.MAINTENANCE);
        inventoryService.capInventory(room.getId(), (int) Math.min(newQuantity, nonMaintenance));
    }

    public RoomUnitResponse setCoverImage(Long roomId, Long unitId, String imageUrl) {
        Room room = findOwnedRoom(roomId);
        RoomUnit unit = findUnit(unitId, room.getId());
        unit.setCoverImageUrl(imageUrl);
        return mapToResponse(unit);
    }

    // ── Summary (used by RoomService when mapping RoomResponse) ──────────

    @Transactional(readOnly = true)
    public RoomUnitSummaryResponse getSummary(Long roomId) {
        List<RoomUnitRepository.RoomUnitSummaryRow> rows =
                roomUnitRepository.summarizeByRoomIds(List.of(roomId));
        if (rows.isEmpty()) {
            return new RoomUnitSummaryResponse(0, 0, 0, 0, 0);
        }
        RoomUnitRepository.RoomUnitSummaryRow row = rows.get(0);
        return new RoomUnitSummaryResponse(
                row.getTotalCount(), row.getAvailableCount(),
                row.getOccupiedCount(), row.getMaintenanceCount(),
                row.getCleaningCount());
    }

    /**
     * Danh sách phòng vật lý của cơ sở kèm trạng thái SUY RA cho một ngày.
     * {@code date == null} → dùng hôm nay. Trạng thái lấy từ assignment phủ ngày đó
     * (booking đang active → RESERVED/OCCUPIED; bảo trì/khoá → MAINTENANCE), nếu
     * không có assignment thì rơi về trạng thái thủ công lưu trên phòng.
     */
    @Transactional(readOnly = true)
    public List<HotelRoomUnitResponse> getUnitsByHotel(Long hotelId, LocalDate date) {
        Hotel hotel = hotelRepository.findById(hotelId)
                .orElseThrow(() -> new ApiException(ErrorCode.NOT_FOUND, "Không tìm thấy cơ sở lưu trú"));
        Long currentUserId = securityService.getCurrentPrincipal().userId();
        if (!hotel.getOwner().getId().equals(currentUserId)) {
            throw new ApiException(ErrorCode.FORBIDDEN);
        }

        LocalDate today = LocalDate.now();
        LocalDate effectiveDate = date != null ? date : today;

        // Gom assignment phủ ngày → mỗi phòng giữ 1 assignment ưu tiên (bảo trì > booking)
        Map<Long, RoomUnitAssignment> byUnit = new HashMap<>();
        for (RoomUnitAssignment a : assignmentRepository.findCoveringDateByHotel(hotelId, effectiveDate, ACTIVE_STATUSES)) {
            byUnit.merge(a.getRoomUnit().getId(), a, (cur, cand) -> priority(cand) > priority(cur) ? cand : cur);
        }

        // findByHotelId already filters out INACTIVE rooms via JPQL
        return roomUnitRepository.findByHotelId(hotelId)
                .stream()
                .map(u -> mapToHotelResponse(u, effectiveDate, today, byUnit.get(u.getId())))
                .toList();
    }

    private static int priority(RoomUnitAssignment a) {
        return a.getType() == AssignmentType.BOOKING ? 1 : 2; // bảo trì/khoá thắng booking
    }

    private RoomUnitStatus deriveStatus(RoomUnit unit, LocalDate effectiveDate, LocalDate today, RoomUnitAssignment a) {
        if (a != null) {
            if (a.getType() == AssignmentType.BOOKING) {
                Booking b = a.getBooking();
                return (b != null && b.getStatus() == BookingStatus.CHECKED_IN)
                        ? RoomUnitStatus.OCCUPIED : RoomUnitStatus.RESERVED;
            }
            return RoomUnitStatus.MAINTENANCE;
        }
        // Không có assignment cho ngày này → trạng thái thủ công lưu trên phòng
        if (unit.getStatus() == RoomUnitStatus.MAINTENANCE) return RoomUnitStatus.MAINTENANCE;
        if (unit.getStatus() == RoomUnitStatus.CLEANING && effectiveDate.isEqual(today)) return RoomUnitStatus.CLEANING;
        return RoomUnitStatus.AVAILABLE;
    }

    // ── Helpers ───────────────────────────────────────────────────────────

    private Room findOwnedRoom(Long roomId) {
        Room room = roomRepository.findById(roomId)
                .orElseThrow(() -> new ApiException(ErrorCode.NOT_FOUND, "Không tìm thấy loại phòng"));
        Long currentUserId = securityService.getCurrentPrincipal().userId();
        if (!room.getHotel().getOwner().getId().equals(currentUserId)) {
            throw new ApiException(ErrorCode.FORBIDDEN);
        }
        return room;
    }

    // Locked variant for create() only: serialises the count-then-insert window at DB level.
    private Room findOwnedRoomForUpdate(Long roomId) {
        Room room = roomRepository.findByIdForUpdate(roomId)
                .orElseThrow(() -> new ApiException(ErrorCode.NOT_FOUND, "Không tìm thấy loại phòng"));
        Long currentUserId = securityService.getCurrentPrincipal().userId();
        if (!room.getHotel().getOwner().getId().equals(currentUserId)) {
            throw new ApiException(ErrorCode.FORBIDDEN);
        }
        return room;
    }

    private RoomUnit findUnit(Long unitId, Long roomId) {
        return roomUnitRepository.findByIdAndRoomId(unitId, roomId)
                .orElseThrow(() -> new ApiException(ErrorCode.NOT_FOUND, "Không tìm thấy phòng cụ thể"));
    }

    private RoomUnitResponse mapToResponse(RoomUnit unit) {
        return new RoomUnitResponse(
                unit.getId(),
                unit.getRoom().getId(),
                unit.getRoomNumber(),
                unit.getFloor(),
                unit.getStatus(),
                unit.getNotes(),
                unit.getGuestName(),
                unit.getCoverImageUrl(),
                unit.isAutoGenerated(),
                unit.getCreatedAt(),
                unit.getUpdatedAt()
        );
    }

    private HotelRoomUnitResponse mapToHotelResponse(
            RoomUnit unit, LocalDate effectiveDate, LocalDate today, RoomUnitAssignment a) {
        Room room = unit.getRoom();
        RoomUnitStatus status = deriveStatus(unit, effectiveDate, today, a);

        boolean booking = a != null && a.getType() == AssignmentType.BOOKING;
        String guestName = booking ? a.getGuestName() : null;
        String notes = a != null ? a.getNote() : unit.getNotes();

        return new HotelRoomUnitResponse(
                unit.getId(),
                room.getId(),
                room.getName(),
                room.getRoomCategory(),
                room.getCoverImageUrl(),
                unit.getRoomNumber(),
                unit.getFloor(),
                status,
                notes,
                guestName,
                unit.getCoverImageUrl(),
                unit.isAutoGenerated(),
                unit.getCreatedAt(),
                unit.getUpdatedAt(),
                effectiveDate,
                a != null && a.getBooking() != null ? a.getBooking().getId() : null,
                a != null ? a.getType() : null,
                a != null ? a.getId() : null
        );
    }
}
