package com.hotel.hotel_backend.service;

import com.hotel.hotel_backend.dto.request.CreateRoomUnitRequest;
import com.hotel.hotel_backend.dto.request.UpdateRoomUnitRequest;
import com.hotel.hotel_backend.dto.response.HotelRoomUnitResponse;
import com.hotel.hotel_backend.dto.response.RoomUnitResponse;
import com.hotel.hotel_backend.dto.response.RoomUnitSummaryResponse;
import com.hotel.hotel_backend.entity.Hotel;
import com.hotel.hotel_backend.entity.Room;
import com.hotel.hotel_backend.entity.RoomUnit;
import com.hotel.hotel_backend.entity.RoomUnitStatus;
import com.hotel.hotel_backend.exception.ApiException;
import com.hotel.hotel_backend.exception.ErrorCode;
import com.hotel.hotel_backend.repository.HotelRepository;
import com.hotel.hotel_backend.repository.RoomRepository;
import com.hotel.hotel_backend.repository.RoomUnitRepository;
import com.hotel.hotel_backend.service.InventoryService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
@RequiredArgsConstructor
@Transactional
public class RoomUnitService {

    private final RoomUnitRepository roomUnitRepository;
    private final RoomRepository roomRepository;
    private final HotelRepository hotelRepository;
    private final SecurityService securityService;
    private final InventoryService inventoryService;

    @Transactional(readOnly = true)
    public List<RoomUnitResponse> getUnits(Long roomId) {
        Room room = findOwnedRoom(roomId);
        return roomUnitRepository.findByRoomIdOrderByFloorAscRoomNumberAsc(room.getId())
                .stream()
                .map(this::mapToResponse)
                .toList();
    }

    public RoomUnitResponse create(Long roomId, CreateRoomUnitRequest request) {
        // Acquire row-level write lock to prevent TOCTOU race on the capacity check.
        Room room = findOwnedRoomForUpdate(roomId);

        if (request.roomNumber() != null && !request.roomNumber().isBlank()) {
            String normalized = request.roomNumber().trim();
            Long hotelId = room.getHotel().getId();
            if (roomUnitRepository.countByHotelIdAndRoomNumber(hotelId, normalized, null) > 0) {
                throw new ApiException(ErrorCode.CONFLICT,
                        "Số phòng \"" + normalized + "\" đã tồn tại trong cơ sở này");
            }
        }

        long currentCount = roomUnitRepository.countByRoomId(room.getId());
        if (currentCount >= room.getQuantity()) {
            throw new ApiException(ErrorCode.VALIDATION_ERROR,
                    "Đã đủ " + room.getQuantity() + " phòng theo cấu hình loại phòng. " +
                    "Hãy tăng số lượng trong cài đặt loại phòng trước.");
        }

        RoomUnitStatus initialStatus = request.status() != null ? request.status() : RoomUnitStatus.AVAILABLE;

        RoomUnit unit = new RoomUnit();
        unit.setRoom(room);
        unit.setRoomNumber(request.roomNumber() == null ? null : request.roomNumber().trim());
        unit.setFloor(request.floor());
        unit.setStatus(initialStatus);
        unit.setNotes(request.notes());
        unit.setGuestName(request.guestName());
        unit.setAutoGenerated(false);

        roomUnitRepository.save(unit);

        if (initialStatus == RoomUnitStatus.MAINTENANCE) {
            long nonMaintenance = roomUnitRepository.countByRoomIdAndStatusNot(
                    room.getId(), RoomUnitStatus.MAINTENANCE);
            inventoryService.capInventory(room.getId(), (int) nonMaintenance);
        }

        return mapToResponse(unit);
    }

    public RoomUnitResponse update(Long roomId, Long unitId, UpdateRoomUnitRequest request) {
        Room room = findOwnedRoom(roomId);
        RoomUnit unit = findUnit(unitId, room.getId());

        if ((request.status() == RoomUnitStatus.RESERVED || request.status() == RoomUnitStatus.OCCUPIED)
                && (unit.getStatus() == RoomUnitStatus.RESERVED || unit.getStatus() == RoomUnitStatus.OCCUPIED)
                && unit.getNotes() != null && !unit.getNotes().isBlank()
                && request.notes() != null && !request.notes().isBlank()
                && !unit.getNotes().equals(request.notes())) {
            throw new ApiException(ErrorCode.CONFLICT,
                    "Phòng này đã được gán cho một booking khác. Vui lòng chọn phòng khác.");
        }

        if (request.roomNumber() != null && !request.roomNumber().isBlank()) {
            String normalized = request.roomNumber().trim();
            Long hotelId = room.getHotel().getId();
            if (roomUnitRepository.countByHotelIdAndRoomNumber(hotelId, normalized, unit.getId()) > 0) {
                throw new ApiException(ErrorCode.CONFLICT,
                        "Số phòng \"" + normalized + "\" đã tồn tại trong cơ sở này");
            }
            unit.setRoomNumber(normalized);
        } else {
            unit.setRoomNumber(null);
        }

        RoomUnitStatus oldStatus = unit.getStatus();
        RoomUnitStatus newStatus = request.status();

        unit.setFloor(request.floor());
        unit.setStatus(newStatus);
        unit.setNotes(request.notes());
        unit.setGuestName(request.guestName());
        unit.setCoverImageUrl(request.coverImageUrl());

        // Sync DailyInventory when transitioning to/from MAINTENANCE.
        // MAINTENANCE phòng bị tắt hoạt động → giảm availableRooms để tránh overbooking.
        // Khi phục hồi → tăng lại 1 slot, không vượt Room.quantity.
        if (oldStatus != newStatus) {
            boolean wasInMaintenance = oldStatus == RoomUnitStatus.MAINTENANCE;
            boolean isInMaintenance  = newStatus == RoomUnitStatus.MAINTENANCE;
            if (wasInMaintenance != isInMaintenance) {
                long nonMaintenance = roomUnitRepository.countByRoomIdAndStatusNot(
                        room.getId(), RoomUnitStatus.MAINTENANCE);
                if (isInMaintenance) {
                    inventoryService.capInventory(room.getId(), (int) nonMaintenance);
                } else {
                    inventoryService.restoreOneUnit(room.getId(), room.getQuantity());
                }
            }
        }

        return mapToResponse(unit);
    }

    public void delete(Long roomId, Long unitId) {
        Room room = findOwnedRoom(roomId);
        RoomUnit unit = findUnit(unitId, room.getId());

        if (unit.getStatus() == RoomUnitStatus.OCCUPIED) {
            throw new ApiException(ErrorCode.VALIDATION_ERROR,
                    "Không thể xóa phòng đang có khách. " +
                    "Đảm bảo khách đã trả phòng và trạng thái không còn là OCCUPIED trước khi xóa.");
        }

        roomUnitRepository.delete(unit);

        // Decrement declared quantity to match actual physical count.
        int newQuantity = Math.max(0, room.getQuantity() - 1);
        room.setQuantity(newQuantity);

        // Re-sync DailyInventory after quantity drops using a single bulk UPDATE query.
        inventoryService.capInventory(room.getId(), newQuantity);
    }

    public RoomUnitResponse setCoverImage(Long roomId, Long unitId, String imageUrl) {
        Room room = findOwnedRoom(roomId);
        RoomUnit unit = findUnit(unitId, room.getId());
        unit.setCoverImageUrl(imageUrl);
        return mapToResponse(unit);
    }

    // ── Summary (used by RoomService when mapping RoomResponse) ──────────

    @Transactional(readOnly = true)
    public RoomUnitSummaryResponse getSummary(Long roomId) {
        List<RoomUnitRepository.RoomUnitSummaryRow> rows =
                roomUnitRepository.summarizeByRoomIds(List.of(roomId));
        if (rows.isEmpty()) {
            return new RoomUnitSummaryResponse(0, 0, 0, 0, 0);
        }
        RoomUnitRepository.RoomUnitSummaryRow row = rows.get(0);
        return new RoomUnitSummaryResponse(
                row.getTotalCount(), row.getAvailableCount(),
                row.getOccupiedCount(), row.getMaintenanceCount(),
                row.getCleaningCount());
    }

    @Transactional(readOnly = true)
    public List<HotelRoomUnitResponse> getUnitsByHotel(Long hotelId) {
        Hotel hotel = hotelRepository.findById(hotelId)
                .orElseThrow(() -> new ApiException(ErrorCode.NOT_FOUND, "Không tìm thấy cơ sở lưu trú"));
        Long currentUserId = securityService.getCurrentPrincipal().userId();
        if (!hotel.getOwner().getId().equals(currentUserId)) {
            throw new ApiException(ErrorCode.FORBIDDEN);
        }
        // findByHotelId already filters out INACTIVE rooms via JPQL
        return roomUnitRepository.findByHotelId(hotelId)
                .stream()
                .map(this::mapToHotelResponse)
                .toList();
    }

    // ── Helpers ───────────────────────────────────────────────────────────

    private Room findOwnedRoom(Long roomId) {
        Room room = roomRepository.findById(roomId)
                .orElseThrow(() -> new ApiException(ErrorCode.NOT_FOUND, "Không tìm thấy loại phòng"));
        Long currentUserId = securityService.getCurrentPrincipal().userId();
        if (!room.getHotel().getOwner().getId().equals(currentUserId)) {
            throw new ApiException(ErrorCode.FORBIDDEN);
        }
        return room;
    }

    // Locked variant for create() only: serialises the count-then-insert window at DB level.
    private Room findOwnedRoomForUpdate(Long roomId) {
        Room room = roomRepository.findByIdForUpdate(roomId)
                .orElseThrow(() -> new ApiException(ErrorCode.NOT_FOUND, "Không tìm thấy loại phòng"));
        Long currentUserId = securityService.getCurrentPrincipal().userId();
        if (!room.getHotel().getOwner().getId().equals(currentUserId)) {
            throw new ApiException(ErrorCode.FORBIDDEN);
        }
        return room;
    }

    private RoomUnit findUnit(Long unitId, Long roomId) {
        return roomUnitRepository.findByIdAndRoomId(unitId, roomId)
                .orElseThrow(() -> new ApiException(ErrorCode.NOT_FOUND, "Không tìm thấy phòng cụ thể"));
    }

    private RoomUnitResponse mapToResponse(RoomUnit unit) {
        return new RoomUnitResponse(
                unit.getId(),
                unit.getRoom().getId(),
                unit.getRoomNumber(),
                unit.getFloor(),
                unit.getStatus(),
                unit.getNotes(),
                unit.getGuestName(),
                unit.getCoverImageUrl(),
                unit.isAutoGenerated(),
                unit.getCreatedAt(),
                unit.getUpdatedAt()
        );
    }

    private HotelRoomUnitResponse mapToHotelResponse(RoomUnit unit) {
        Room room = unit.getRoom();
        return new HotelRoomUnitResponse(
                unit.getId(),
                room.getId(),
                room.getName(),
                room.getRoomCategory(),
                room.getCoverImageUrl(),
                unit.getRoomNumber(),
                unit.getFloor(),
                unit.getStatus(),
                unit.getNotes(),
                unit.getGuestName(),
                unit.getCoverImageUrl(),
                unit.isAutoGenerated(),
                unit.getCreatedAt(),
                unit.getUpdatedAt()
        );
    }
}
